<?php
/**
 * BuyerApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KeyCRM OpenAPI documentation
 *
 * Опис REST маршрутів для роботи з KeyCRM OpenAPI.<br><br> <b>Зверніть увагу:</b> <br> 1. Для авторизації потрібно передавати заголовок у форматі Bearer + <a href=\"https://help.keycrm.app/uk/process-automation-api-and-more/where-to-get-an-api-key\" target=\"_blank\">APIkey</a> (authorization:[Bearer `ваш-API-ключ`]); <br> 2. Є обмеження до 60 запитів на хвилину з однієї IP-адреси по API-ключу; <br> 3. Час у всіх сутностях використовується UTC (GMT+0) - при зчитуванні (GET-запити), при виборі (фільтрації) по часу створення сутності, а також при створенні сутностей (POST).
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * BuyerApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BuyerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createNewBuyer' => [
            'application/json',
        ],
        'getBuyerById' => [
            'application/json',
        ],
        'getPaginatedListOfBuyers' => [
            'application/json',
        ],
        'importBuyers' => [
            'application/json',
        ],
        'updateExistingBuyer' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createNewBuyer
     *
     * Створення нового покупця
     *
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для створення нового покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNewBuyer'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Buyer
     */
    public function createNewBuyer($update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['createNewBuyer'][0])
    {
        list($response) = $this->createNewBuyerWithHttpInfo($update_existing_buyer_request, $accept, $contentType);
        return $response;
    }

    /**
     * Operation createNewBuyerWithHttpInfo
     *
     * Створення нового покупця
     *
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для створення нового покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNewBuyer'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Buyer, HTTP status code, HTTP response headers (array of strings)
     */
    public function createNewBuyerWithHttpInfo($update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['createNewBuyer'][0])
    {
        $request = $this->createNewBuyerRequest($update_existing_buyer_request, $accept, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\Buyer' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Buyer' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Buyer', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\Buyer';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Buyer',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createNewBuyerAsync
     *
     * Створення нового покупця
     *
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для створення нового покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNewBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNewBuyerAsync($update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['createNewBuyer'][0])
    {
        return $this->createNewBuyerAsyncWithHttpInfo($update_existing_buyer_request, $accept, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createNewBuyerAsyncWithHttpInfo
     *
     * Створення нового покупця
     *
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для створення нового покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNewBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNewBuyerAsyncWithHttpInfo($update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['createNewBuyer'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Buyer';
        $request = $this->createNewBuyerRequest($update_existing_buyer_request, $accept, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createNewBuyer'
     *
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для створення нового покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createNewBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createNewBuyerRequest($update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['createNewBuyer'][0])
    {

        // verify the required parameter 'update_existing_buyer_request' is set
        if ($update_existing_buyer_request === null || (is_array($update_existing_buyer_request) && count($update_existing_buyer_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_existing_buyer_request when calling createNewBuyer'
            );
        }



        $resourcePath = '/buyer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_existing_buyer_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_existing_buyer_request));
            } else {
                $httpBody = $update_existing_buyer_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBuyerById
     *
     * Отримання сутності покупця за ідентифікатором
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuyerById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BuyerWithIncludes
     */
    public function getBuyerById($buyer_id, $accept = null, $include = null, string $contentType = self::contentTypes['getBuyerById'][0])
    {
        list($response) = $this->getBuyerByIdWithHttpInfo($buyer_id, $accept, $include, $contentType);
        return $response;
    }

    /**
     * Operation getBuyerByIdWithHttpInfo
     *
     * Отримання сутності покупця за ідентифікатором
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuyerById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BuyerWithIncludes, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBuyerByIdWithHttpInfo($buyer_id, $accept = null, $include = null, string $contentType = self::contentTypes['getBuyerById'][0])
    {
        $request = $this->getBuyerByIdRequest($buyer_id, $accept, $include, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\BuyerWithIncludes' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\BuyerWithIncludes' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BuyerWithIncludes', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\BuyerWithIncludes';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BuyerWithIncludes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBuyerByIdAsync
     *
     * Отримання сутності покупця за ідентифікатором
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuyerById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuyerByIdAsync($buyer_id, $accept = null, $include = null, string $contentType = self::contentTypes['getBuyerById'][0])
    {
        return $this->getBuyerByIdAsyncWithHttpInfo($buyer_id, $accept, $include, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBuyerByIdAsyncWithHttpInfo
     *
     * Отримання сутності покупця за ідентифікатором
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuyerById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuyerByIdAsyncWithHttpInfo($buyer_id, $accept = null, $include = null, string $contentType = self::contentTypes['getBuyerById'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BuyerWithIncludes';
        $request = $this->getBuyerByIdRequest($buyer_id, $accept, $include, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBuyerById'
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuyerById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBuyerByIdRequest($buyer_id, $accept = null, $include = null, string $contentType = self::contentTypes['getBuyerById'][0])
    {

        // verify the required parameter 'buyer_id' is set
        if ($buyer_id === null || (is_array($buyer_id) && count($buyer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $buyer_id when calling getBuyerById'
            );
        }




        $resourcePath = '/buyer/{buyerId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }

        // path params
        if ($buyer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'buyerId' . '}',
                ObjectSerializer::toPathValue($buyer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPaginatedListOfBuyers
     *
     * Отримання списку покупців
     *
     * @param  string $accept application/json (optional)
     * @param  int $limit Максимальна кількість елементів у пагінованому списку. Максимум 50. (optional, default to 15)
     * @param  int $page Вкажіть сторінку (optional, default to 1)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  object $filter Фільтрація списку покупців (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaginatedListOfBuyers'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response
     */
    public function getPaginatedListOfBuyers($accept = null, $limit = 15, $page = 1, $include = null, $filter = null, string $contentType = self::contentTypes['getPaginatedListOfBuyers'][0])
    {
        list($response) = $this->getPaginatedListOfBuyersWithHttpInfo($accept, $limit, $page, $include, $filter, $contentType);
        return $response;
    }

    /**
     * Operation getPaginatedListOfBuyersWithHttpInfo
     *
     * Отримання списку покупців
     *
     * @param  string $accept application/json (optional)
     * @param  int $limit Максимальна кількість елементів у пагінованому списку. Максимум 50. (optional, default to 15)
     * @param  int $page Вкажіть сторінку (optional, default to 1)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  object $filter Фільтрація списку покупців (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaginatedListOfBuyers'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaginatedListOfBuyersWithHttpInfo($accept = null, $limit = 15, $page = 1, $include = null, $filter = null, string $contentType = self::contentTypes['getPaginatedListOfBuyers'][0])
    {
        $request = $this->getPaginatedListOfBuyersRequest($accept, $limit, $page, $include, $filter, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPaginatedListOfBuyersAsync
     *
     * Отримання списку покупців
     *
     * @param  string $accept application/json (optional)
     * @param  int $limit Максимальна кількість елементів у пагінованому списку. Максимум 50. (optional, default to 15)
     * @param  int $page Вкажіть сторінку (optional, default to 1)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  object $filter Фільтрація списку покупців (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaginatedListOfBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaginatedListOfBuyersAsync($accept = null, $limit = 15, $page = 1, $include = null, $filter = null, string $contentType = self::contentTypes['getPaginatedListOfBuyers'][0])
    {
        return $this->getPaginatedListOfBuyersAsyncWithHttpInfo($accept, $limit, $page, $include, $filter, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaginatedListOfBuyersAsyncWithHttpInfo
     *
     * Отримання списку покупців
     *
     * @param  string $accept application/json (optional)
     * @param  int $limit Максимальна кількість елементів у пагінованому списку. Максимум 50. (optional, default to 15)
     * @param  int $page Вкажіть сторінку (optional, default to 1)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  object $filter Фільтрація списку покупців (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaginatedListOfBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaginatedListOfBuyersAsyncWithHttpInfo($accept = null, $limit = 15, $page = 1, $include = null, $filter = null, string $contentType = self::contentTypes['getPaginatedListOfBuyers'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetPaginatedListOfBuyers200Response';
        $request = $this->getPaginatedListOfBuyersRequest($accept, $limit, $page, $include, $filter, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaginatedListOfBuyers'
     *
     * @param  string $accept application/json (optional)
     * @param  int $limit Максимальна кількість елементів у пагінованому списку. Максимум 50. (optional, default to 15)
     * @param  int $page Вкажіть сторінку (optional, default to 1)
     * @param  string $include Підключення додаткових асоціацій, розділені комами. Приклад: &lt;strong&gt;manager,company&lt;/strong&gt; &lt;br/&gt;&lt;br/&gt; Допустимі асоціації &#x60;manager&#x60;, &#x60;shipping&#x60;, &#x60;company&#x60;, &#x60;loyalty&#x60;, &#x60;custom_fields&#x60; (optional)
     * @param  object $filter Фільтрація списку покупців (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaginatedListOfBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaginatedListOfBuyersRequest($accept = null, $limit = 15, $page = 1, $include = null, $filter = null, string $contentType = self::contentTypes['getPaginatedListOfBuyers'][0])
    {


        if ($limit !== null && $limit > 50) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BuyerApi.getPaginatedListOfBuyers, must be smaller than or equal to 50.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BuyerApi.getPaginatedListOfBuyers, must be bigger than or equal to 1.');
        }
        




        $resourcePath = '/buyer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'object', // openApiType
            'deepObject', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation importBuyers
     *
     * Імпорт покупців
     *
     * @param  \OpenAPI\Client\Model\ImportBuyersRequest $import_buyers_request Приклад об&#39;єкту запиту для імпорту покупців (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importBuyers'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AttachTagToOrder202Response|\OpenAPI\Client\Model\ImportBuyers400Response
     */
    public function importBuyers($import_buyers_request, $accept = null, string $contentType = self::contentTypes['importBuyers'][0])
    {
        list($response) = $this->importBuyersWithHttpInfo($import_buyers_request, $accept, $contentType);
        return $response;
    }

    /**
     * Operation importBuyersWithHttpInfo
     *
     * Імпорт покупців
     *
     * @param  \OpenAPI\Client\Model\ImportBuyersRequest $import_buyers_request Приклад об&#39;єкту запиту для імпорту покупців (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importBuyers'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AttachTagToOrder202Response|\OpenAPI\Client\Model\ImportBuyers400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function importBuyersWithHttpInfo($import_buyers_request, $accept = null, string $contentType = self::contentTypes['importBuyers'][0])
    {
        $request = $this->importBuyersRequest($import_buyers_request, $accept, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\AttachTagToOrder202Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AttachTagToOrder202Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AttachTagToOrder202Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\ImportBuyers400Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ImportBuyers400Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ImportBuyers400Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\AttachTagToOrder202Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AttachTagToOrder202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ImportBuyers400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation importBuyersAsync
     *
     * Імпорт покупців
     *
     * @param  \OpenAPI\Client\Model\ImportBuyersRequest $import_buyers_request Приклад об&#39;єкту запиту для імпорту покупців (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importBuyersAsync($import_buyers_request, $accept = null, string $contentType = self::contentTypes['importBuyers'][0])
    {
        return $this->importBuyersAsyncWithHttpInfo($import_buyers_request, $accept, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation importBuyersAsyncWithHttpInfo
     *
     * Імпорт покупців
     *
     * @param  \OpenAPI\Client\Model\ImportBuyersRequest $import_buyers_request Приклад об&#39;єкту запиту для імпорту покупців (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importBuyersAsyncWithHttpInfo($import_buyers_request, $accept = null, string $contentType = self::contentTypes['importBuyers'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AttachTagToOrder202Response';
        $request = $this->importBuyersRequest($import_buyers_request, $accept, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'importBuyers'
     *
     * @param  \OpenAPI\Client\Model\ImportBuyersRequest $import_buyers_request Приклад об&#39;єкту запиту для імпорту покупців (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importBuyers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function importBuyersRequest($import_buyers_request, $accept = null, string $contentType = self::contentTypes['importBuyers'][0])
    {

        // verify the required parameter 'import_buyers_request' is set
        if ($import_buyers_request === null || (is_array($import_buyers_request) && count($import_buyers_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $import_buyers_request when calling importBuyers'
            );
        }



        $resourcePath = '/buyer/import';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($import_buyers_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($import_buyers_request));
            } else {
                $httpBody = $import_buyers_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateExistingBuyer
     *
     * Оновлення існуючого покупця
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для оновлення покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateExistingBuyer'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Buyer
     */
    public function updateExistingBuyer($buyer_id, $update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['updateExistingBuyer'][0])
    {
        list($response) = $this->updateExistingBuyerWithHttpInfo($buyer_id, $update_existing_buyer_request, $accept, $contentType);
        return $response;
    }

    /**
     * Operation updateExistingBuyerWithHttpInfo
     *
     * Оновлення існуючого покупця
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для оновлення покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateExistingBuyer'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Buyer, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateExistingBuyerWithHttpInfo($buyer_id, $update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['updateExistingBuyer'][0])
    {
        $request = $this->updateExistingBuyerRequest($buyer_id, $update_existing_buyer_request, $accept, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    if ('\OpenAPI\Client\Model\Buyer' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Buyer' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Buyer', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\Buyer';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Buyer',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateExistingBuyerAsync
     *
     * Оновлення існуючого покупця
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для оновлення покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateExistingBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateExistingBuyerAsync($buyer_id, $update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['updateExistingBuyer'][0])
    {
        return $this->updateExistingBuyerAsyncWithHttpInfo($buyer_id, $update_existing_buyer_request, $accept, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateExistingBuyerAsyncWithHttpInfo
     *
     * Оновлення існуючого покупця
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для оновлення покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateExistingBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateExistingBuyerAsyncWithHttpInfo($buyer_id, $update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['updateExistingBuyer'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Buyer';
        $request = $this->updateExistingBuyerRequest($buyer_id, $update_existing_buyer_request, $accept, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateExistingBuyer'
     *
     * @param  string $buyer_id Ідентифікатор покупця (required)
     * @param  \OpenAPI\Client\Model\UpdateExistingBuyerRequest $update_existing_buyer_request Приклад об&#39;єкту запиту для оновлення покупця (required)
     * @param  string $accept application/json (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateExistingBuyer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateExistingBuyerRequest($buyer_id, $update_existing_buyer_request, $accept = null, string $contentType = self::contentTypes['updateExistingBuyer'][0])
    {

        // verify the required parameter 'buyer_id' is set
        if ($buyer_id === null || (is_array($buyer_id) && count($buyer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $buyer_id when calling updateExistingBuyer'
            );
        }

        // verify the required parameter 'update_existing_buyer_request' is set
        if ($update_existing_buyer_request === null || (is_array($update_existing_buyer_request) && count($update_existing_buyer_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_existing_buyer_request when calling updateExistingBuyer'
            );
        }



        $resourcePath = '/buyer/{buyerId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }

        // path params
        if ($buyer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'buyerId' . '}',
                ObjectSerializer::toPathValue($buyer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_existing_buyer_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_existing_buyer_request));
            } else {
                $httpBody = $update_existing_buyer_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
